# Generated by Django 6.0.5 on 2026-06-14 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prerequisite',
            name='min_grade',
            field=models.DecimalField(blank=True, decimal_places=2, default=10.0, max_digits=4, null=True),
        ),
    ]
