# Generated by Django 6.0.5 on 2026-06-15 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_prerequisite_min_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classschedule',
            name='day_of_week',
            field=models.CharField(blank=True, choices=[('sat', 'Saturday'), ('sun', 'Sunday'), ('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', 'Friday')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('professional', 'Professional'), ('base', 'Base'), ('lab', 'Laboratory'), ('public', 'Public')], max_length=20),
        ),
        migrations.AlterField(
            model_name='courseoffering',
            name='status',
            field=models.CharField(choices=[('can', 'Can'), ('cant', "Can't")], default='can', max_length=20),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(blank=True, choices=[('accepted', 'Accepted'), ('final', 'Final'), ('temp', 'Temporary'), ('delete', 'Deleted'), ('not_accepted', 'Not Accepted')], default='temp', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='grade_type',
            field=models.CharField(choices=[('midterm', 'Midterm'), ('quiz', 'Quiz'), ('final', 'Final'), ('lastterm', 'Last Term'), ('homework', 'Homework')], max_length=30),
        ),
        migrations.AlterField(
            model_name='prerequisite',
            name='pre_type',
            field=models.CharField(blank=True, choices=[('pre', 'Pre'), ('together', 'Together')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='professor',
            name='academic_rank',
            field=models.CharField(blank=True, choices=[('TA', 'ta'), ('professor', 'Professor')], max_length=20, null=True),
        ),
    ]
