# Generated by Django 6.0.5 on 2026-06-15 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_classschedule_day_of_week_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='classschedule',
            name='class_dow_check',
        ),
        migrations.RemoveConstraint(
            model_name='course',
            name='course_type_check',
        ),
        migrations.RemoveConstraint(
            model_name='courseoffering',
            name='offering_status_check',
        ),
        migrations.RemoveConstraint(
            model_name='enrollment',
            name='enrollment_status_check',
        ),
        migrations.RemoveConstraint(
            model_name='grade',
            name='grade_type_check',
        ),
        migrations.RemoveConstraint(
            model_name='prerequisite',
            name='prerequisite_type_check',
        ),
        migrations.RemoveConstraint(
            model_name='professor',
            name='professor_academic_rank_check',
        ),
    ]
